BookBinder/OCR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookBinder/account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'account'
urlpatterns = [
    path('', views.account, name = 'accdef'),
    path('', views.account, name = 'home'),
    path('login/', views.loginform, name = 'linform'),
    path('dologin/', views.login, name = 'lin'),
    path('signup/', views.signupform, name = 'supform' ),
    path('dosignup/', views.signup, name = 'sup' ),
    path('logout/', views.logout, name = 'lout'),
    path('loginfromand/', views.loginfromand, name = 'linfand'),
    path('logoutfromand/', views.logoutfromand, name = 'loutfand'),
    path('upfromjson/', views.upfromjson, name = 'linfjson'),
    path('downtojson/', views.downtojson, name = 'dwntjson'),
    path(r'deletedata/<isbn>[0-9]{1,13}/', views.deletedata, name = 'deletedata'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookBinder/accounts/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.account, name = 'accdef'),
    path('', views.account, name = 'home'),
    path('login/', views.loginform, name = 'linform'),
    path('dologin/', views.login, name = 'lin'),
    path('signup/', views.signupform, name = 'supform' ),
    path('dosignup/', views.signup, name = 'sup' ),
    path('logout/', views.logout, name = 'lout'),
    path('loginfromand/', views.loginfromand, name = 'linfand'),
    path('logoutfromand/', views.logoutfromand, name = 'loutfand'),
    path('upfromjson/', views.upfromjson, name = 'linfjson'),
    path('downtojson/', views.downtojson, name = 'dwntjson'),
    path(r'deletedata/<isbn>[0-9]{1,13}/', views.deletedata, name = 'deletedata'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookBinder/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Book(models.Model):
    objects = models.Manager()

    owner = models.CharField(max_length = 200, blank = False)
    isbn = models.CharField(max_length = 200, blank = False)
    title = models.CharField(max_length = 200, blank = True)
    booklink = models.CharField(max_length = 200, blank = True)
    author = models.CharField(max_length = 200, blank = True)
    price = models.CharField(max_length = 200, blank = True)
    publisher = models.CharField(max_length = 200, blank = True)
    date = models.CharField(max_length = 200, blank = True)
    imagelink = models.CharField(max_length = 200, blank = True)
    memo = models.CharField(max_length = 200, blank = True, null = False)

    class Meta:
        unique_together = (("owner", "isbn"),)

BookBinder/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Book(models.Model):
    objects = models.Manager()

    owner = models.CharField(max_length = 200, blank = False)
    isbn = models.CharField(max_length = 200, blank = False)
    title = models.CharField(max_length = 200, blank = True)
    booklink = models.CharField(max_length = 200, blank = True)
    author = models.CharField(max_length = 200, blank = True)
    price = models.CharField(max_length = 200, blank = True)
    publisher = models.CharField(max_length = 200, blank = True)
    date = models.CharField(max_length = 200, blank = True)
    imagelink = models.CharField(max_length = 200, blank = True)
    memo = models.CharField(max_length = 200, blank = True, null = False)

    class Meta:
        unique_together = (("owner", "isbn"),)

BookBinder/account/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.models import User, UserManager
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import Book
import requests
import json
# Create your views here.

def account(request):
    if not request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:linform')
    else:
        user = User.objects.get(username = request.user.username)
        book = Book.objects.all()
        book = Book.objects.filter(owner = user.username)
        count = book.count()
        storage = messages.get_messages(request)
        storage.used = True
        return render(request, 'account/def.html', {'user':user, 'books':book, 'count':count})

def deletedata(request, isbn):
    if not request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:linform')
    else:
        user = User.objects.get(username = request.user.username)
        book = Book.objects.all()
        book = book.filter(owner = user).filter(isbn = isbn)
        book.delete()
        book = Book.objects.filter(owner = user)
        count = book.count()
        storage = messages.get_messages(request)
        storage.used = True
        return render(request, 'account/def.html', {'user':user, 'books':book, 'count':count})

#def readdatafromand(request):

#def senddatatoand(request):

def downtojson(request):
    if request.method=="POST":   
        data = json.loads(request.body)
        username = data['username']
        password = data['password']

        user = auth.authenticate(request, username = username, password = password)
        
        if user is not None:
            try:
                auth.login(request,user)
                book = Book.objects.all().filter( owner = username)
                booklist = serializers.serialize('json', book)
                return HttpResponse(booklist, content_type = "text/json-comment-filtered")
            except:
                return JsonResponse({"result", "LoginFail"}) 
        else:
            return JsonResponse({"result", "LoginFail"}) 
    else:
        return JsonResponse({"result", "LoginFail"}) 


def upfromjson(request):
    data = json.loads(request.body)

    if request.user.is_authenticated:
        return HttpResponse("AlreadyLoginned")
    if request.method == "POST":
        data = json.loads(request.body)
        username = data['username']
        password = data['password']
        isbn = data['isbn']
        title = data['title']
        booklink = data['booklink']
        author = data['author']
        price = data['price']
        publisher = data['publisher']
        date = data['date']
        imagelink = data['imagelink']
        memo = data['memo']

        user = auth.authenticate(request, username = username, password = password)
        
        if user is not None:
            try:
                auth.login(request,user)
                Book.create( owner = username, isbn = isbn, title = title, booklink = booklink, author = author, price = price, publisher = publisher, date = date, imagelink = imagelink, memo = memo )
                return JsonResponse({"title" : title, "result": "success"})
            except:
                book = Book.objects.all()
                book = book.filter( owner = username, isbn = isbn)
                book.delete()
                Book.objects.create( owner = username, isbn = isbn, title = title, booklink = booklink, author = author, price = price, publisher = publisher, date = date, imagelink = imagelink, memo = memo )
                return JsonResponse({"title" : title, "result": "success"})
            else:
                return JsonResponse({"result", "LoginFail"}) 
        else:
            return JsonResponse({"result", "LoginFail"})   
    else:
        return JsonResponse({"result", "LoginFail"})

def loginfromand(request):
    if request.user.is_authenticated:
        return HttpResponse("LoginSuccess")
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username = username, password = password)
        if user is not None:
            try:
                auth.login(request,user)
                return HttpResponse("LoginSuccess")
            except:
                return HttpResponse("LoginFailed")
        else:
            return HttpResponse("LoginFailed")        
    else:
        return HttpResponse("LoginFailed")

@login_required
def logoutfromand(request):
    auth.logout(request)
    return HttpResponse("LogOut")


def login(request):
    if request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:accdef')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username = username, password = password)
        if user is not None:
            auth.login(request, user)
            storage = messages.get_messages(request)
            storage.used = True
            messages.success(request,'로그인 성공!')
            return redirect('account:accdef')
        else:
            storage = messages.get_messages(request)
            storage.used = True
            messages.error(request,'로그인 실패!')
            return redirect('account:linform')        
    else:
        storage = messages.get_messages(request)
        storage.used = True
        messages.error(request, '잘못된 접근입니다')
        return redirect('account:accdef')

def signup(request):
    if request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:accdef')

    if (request.POST["username"] is not None) and (request.method == "POST") and (request.POST["password1"] == request.POST["password2"]):
            try:
                user = User.objects.create_user(
                    username = request.POST["username"],
                    password = request.POST["password1"],
                    email= request.POST["email"]
                )
                auth.login(request,user)
                storage = messages.get_messages(request)
                storage.used = True
                messages.success(request,'회원가입 성공!')
                return redirect(request, 'account:accdef', {'user':user} )
            except:
                storage = messages.get_messages(request)
                storage.used = True
                return redirect('account:supform')
            else:
                storage = messages.get_messages(request)
                storage.used = True
                messages.error(request,'회원가입 실패!')  
                return redirect('account:supform')
    else:
        storage = messages.get_messages(request)
        storage.used = True
        messages.error(request, '잘못된 접근입니다')
        return redirect('account:accdef')

@login_required
def logout(request):
    auth.logout(request)
    return redirect('account:accdef')

def loginform(request):
    if request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:accdef')
    else:
        return render(request, 'account/login.html')

def signupform(request):
    if request.user.is_authenticated:
        storage = messages.get_messages(request)
        storage.used = True
        return redirect('account:accdef')
    else:
        return render(request, 'account/signup.html')

BookBinder/accounts/templates/accounts/def.html
{% extends "accounts/layout.html" %}

{% block title %}
account
{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <div>Username : {{user.username}}</div>
        <div style="text-align: right;">등록된 건수 : {{count}}건</div>
        <br>
        <table class="table" style="text-align: center;">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center;">
                        ISBN
                    </th>
                    <th scope="col" style="text-align: center;">
                        제목
                    </th>
                    <th scope="col" style="text-align: center;">
                        저자
                    </th>
                    <th scope="col" style="text-align: center;">
                        정가
                    </th>
                    <th scope="col" style="text-align: center;">
                        출판사/레이블
                    </th>
                    <th scope="col" style="text-align: center;">
                        발매일
                    </th>
                    <th scope="col" style="text-align: center;">
                        표지
                    </th>
                    <th scope="col" style="text-align: center;">
                        메모
                    </th>
                    <th scope="col" style="text-align: center;">
                        삭제
                    </th>
                </thead>
            </tr>
            {% for bks in books %}
            <tr>
                <td>{{bks.isbn}}</td>
                <td>
                    <a href="{{bks.booklink}}">
                        {{bks.title}}
                    </a>
                </td>
                <td>{{bks.author}}</td>
                <td>{{bks.price}}</td>
                <td>{{bks.publisher}}</td>
                <td>{{bks.date}}</td>
                <td>
                    <a href="{{bks.imagelink}}">
                        <img src="{{bks.imagelink}}" width="75" height="100">
                    </a>
                </td>
                <td>{{bks.memo}}</td>
                <td>
                   <form action="{% url 'accounts:deletedata' bks.isbn %}" method="POST">
                       {% csrf_token %}
                       <input type="submit" value="Delete">
                   </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        <br>
    {% endif %}
</div>
{% endblock %}

BookBinder/accounts/templates/accounts/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
      {% block title %}
      {% endblock %}
    </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'accounts:home' %}">BookBinder</a>
            </div>
            <div class="navbar-nav navbar-right">
                <a class="navbar-brand" href="{% url 'accounts:accdef' %}">메인</a>
            </div>
            {% if user.is_authenticated %}
            <div class="navbar-nav navbar-right">
                <a class="navbar-brand" href="{% url 'accounts:lout' %}">로그아웃</a>
            </div>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
	    {% for message in messages %}
            <script>
    	        alert("{{ message.message }} ")
            </script>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

BookBinder/accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'accounts:lin'%}">
       {% csrf_token %}
       Username:
       <br>
       <input name ="username" type="text">
       <br>
       Password:
       <br>
       <input name="password" type="password">
       <br><br>
       <input type="submit" class="btn btn-primary" value="Sign in">
    </form>
    <br>
    <a href="{% url 'accounts:supform' %}">
        <button type="menu" class="btn btn-primary">Sign up</button>
    </a>
</div>
{% endblock %}

BookBinder/accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block title %}
Sign up
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST" action="{% url 'accounts:sup'%}">
       {% csrf_token %}
       Username:
       <br>
       <input name = "username" type="text">
       <br>
       Password:
       <br>
       <input name="password1" type="password">
       <br>
       Confirm Password:
       <br>
       <input name="password2" type="password">
       <br>
       E-mail
       <br>
       <input name="email" type="email">
       <br><br>
       <input type="submit" class="btn btn-primary" value="Sign up">
    </form>
</div>
{% endblock %}